version: '3.8'
services:
  dev-postgres:
    image: postgres:15.1-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: devUser
      POSTGRES_PASSWORD: devPass
      POSTGRES_DB: devDB
    restart: always
    networks:
      - my_network
networks:
  my_network:
